version: 0.2

phases:
  install:
    commands:
      - echo "Installing NPM dependencies..."
      - npm ci
      - echo "Installing Playwright browsers + Linux dependencies..."
      - npx playwright install --with-deps

  build:
    commands:
      - echo "Running Playwright tests with Allure + HTML reports..."
      - npm run test:chromium
      - echo "Generating Allure HTML report..."
      - npm run allure:report

artifacts:
  files:
    - 'playwright-report/**'
    - 'allure-results/**'
    - 'allure-report/**'
  discard-paths: no
