version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Dependencies..."
      - npm ci
      - npx playwright install --with-deps

  build:
    commands:
      - echo "Running Playwright tests..."
      - npx playwright test

artifacts:
  files:
    - 'playwright-report/**'
  discard-paths: no
