version: 0.2

phases:
  install:
    commands:
      - echo "Installing NPM dependencies..."
      - npm ci
      - echo "Installing Playwright browsers + Linux dependencies..."
      - npx playwright install --with-deps
      - echo "Installing Java for Allure CLI..."
      - apt-get update && apt-get install -y openjdk-17-jdk
      - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version

  build:
    commands:
      - echo "Step 1: Running Playwright tests..."
      - npm run test:chromium || echo "Playwright tests failed, continuing to report generation..."
      - echo "Step 2: Generating Allure HTML report..."
      - npx allure generate my-allure-results --clean -o allure-report || echo "Allure report generation failed"

artifacts:
  files:
    - 'playwright-report/**'
    - 'my-allure-results/**'
    - 'allure-report/**'
  discard-paths: no
