version: 0.2

phases:
  install:
    commands:
      - echo "Installing NPM dependencies..."
      - npm ci

  build:
    commands:
      - echo "Running Playwright tests with Allure + HTML reports..."
      - npm run test:report
      - echo "Generating Allure HTML report..."
      - npx allure generate allure-results --clean -o allure-report

artifacts:
  files:
    - 'playwright-report/**'
    - 'allure-results/**'
    - 'allure-report/**'
  discard-paths: no
