version: 0.2

phases:
  install:
    commands:
      - echo "Installing NPM dependencies..."
      - npm ci
      - echo "Installing Playwright browsers + Linux dependencies..."
      - npx playwright install --with-deps

  build:
    commands:
      - echo "Running Playwright tests..."
      - npm run test:chromium || echo "Playwright tests failed, continuing..."

artifacts:
  ffiles:
    - results/**/*.html
  discard-paths: no
  base-directory: results

