version: 2.1

executors:
  pw-exec:
    docker:
      - image: mcr.microsoft.com/playwright:v1.47.0-jammy
    working_directory: ~/project

jobs:
  test:
    executor: pw-exec
    environment:
      ALLURE_RESULTS_DIR: my-allure-results
    steps:
      - checkout

      - run:
          name: Install deps
          command: npm ci

      - run:
          name: Run Playwright (HTML + Allure + JUnit)
          command: |
            mkdir -p test-results
            npx playwright test --reporter=line,html,allure-playwright,junit || true

      - run:
          name: Generate Allure HTML
          command: |
            if [ -d "$ALLURE_RESULTS_DIR" ] || [ -d "allure-results" ]; then
              DIR="$ALLURE_RESULTS_DIR"; [ ! -d "$DIR" ] && DIR="allure-results"
              npx allure generate "$DIR" --clean -o allure-report || echo "Allure skipped"
            else
              mkdir -p allure-report && printf "<h2>No Allure report</h2>" > allure-report/index.html
            fi

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: junit-xml
      - store_artifacts:
          path: playwright-report
          destination: playwright-html
      - store_artifacts:
          path: allure-report
          destination: allure-html

workflows:
  ci:
    jobs:
      - test
